import re
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
try:
    from src.states import AgentState
    from src.tools import write_code_to_file
except ModuleNotFoundError as error:
    if error.name != "src":
        raise
    from states import AgentState
    from tools import write_code_to_file
import os
import subprocess
import sys
from dotenv import load_dotenv
import tempfile

load_dotenv()

llm = ChatOpenAI(base_url=os.getenv("ENDPOINT_URL"),
                 api_key=os.getenv("OPENAI_API_KEY"),
                 model=os.getenv("DEPLOYMENT_MODEL_NAME"),
                 temperature=0)

def generate_code_node(state: AgentState)->dict:
    """Queries to LLM for valid code structure while passing error contexts.""" 
    print("------GENERATING CODE------")
    prompt = f"Task: {state["task"]}\n"
    if state.get("error"):
        prompt +=f"\n Your previous code failed with this \n error{state["error"]}\n Please fix."

    SYSTEM_PROMPT="""
    You are expert Software Engineer agent. Output ONLY valid, clean code with follwing coding best practice and well structure code.
    Write the code with minimal code and follow that OOPS,SOLID, Test driven code practice. 
    """
    response= llm.invoke([
        {"role": "system", "content": SYSTEM_PROMPT},
        HumanMessage(content=prompt)
    ])

     # Strip accidental markdown code blocks if the LLM hallucinated them
    clean_code = re.sub(r"^```python\n|^```\n|```$", "", response.content, flags=re.MULTILINE).strip()
    return {"generated_code": clean_code, "iterations": state.get("iterations", 0) + 1}


def write_file_node(state: AgentState)-> dict:
    """Take the generated state content and write to the file on disk"""
    print("-------WRITING FILE-------")
    write_code_to_file(state.get("generated_code"), state.get("file_path"))
    return {}


def validate_code_node(state: AgentState) -> dict:
    """Validates generated code dynamically based on the target programming language."""
    print(f"--- VALIDATING {state['language'].upper()} CODE ---")
    
    code = state["generated_code"]
    lang = state["language"].lower().strip()
    
    # 1. Handle Python Validation (In-memory evaluation)
    if lang == "python":
        try:
            compile(code, "<string>", "exec")
            return {"error_message": None}
        except Exception as e:
            return {"error_message": f"Python Syntax Error: {str(e)}"}
        
    # --- 3. .NET / C# Validation ---
    elif lang in ["c#", "csharp", ".net", "dotnet"]:
        with tempfile.TemporaryDirectory() as tmpdir:
            try:
                # Initialize a minimal, clean .NET console app inside the temp directory
                # '--no-restore' flag is skipped initially to fetch fundamental compiler targets
                subprocess.run(
                    ["dotnet", "new", "console", "-n", "ValidateApp", "-o", tmpdir], 
                    capture_output=True, 
                    text=True, 
                    check=True
                )
                
                # Path to the primary entry code file generated by the .NET template
                program_cs_path = os.path.join(tmpdir, "Program.cs")
                
                # Replace the template text with the AI-generated C# code block
                with open(program_cs_path, "w", encoding="utf-8") as f:
                    f.write(code)
                
                # Trigger dry run build compilation to catch architectural/syntax breakages
                # 'no-incremental' guarantees it compiles fully fresh without caching flags
                build_result = subprocess.run(
                    ["dotnet", "build", tmpdir, "/clp:ErrorsOnly", "--no-incremental"], 
                    capture_output=True, 
                    text=True
                )
                
                if build_result.returncode != 0:
                    return {"error_message": f".NET Build Compilation Failed:\n{build_result.stdout.strip()}"}
                
                return {"error_message": None}
                
            except subprocess.CalledProcessError as e:
                # Catches internal .NET core setup tool failures (e.g., SDK conflicts)
                return {"error_message": f"Failed initializing .NET sandbox workspace: {e.stderr}"}
       
    # 2. Handle JavaScript / TypeScript Validation (Using Node.js CLI)
    elif lang in ["javascript", "js"]:
        # 'node -c' checks syntax without running the actual code logic
        result = subprocess.run(
            ["node", "-c"], 
            input=code, 
            text=True, 
            capture_output=True
        )
        if result.returncode != 0:
            return {"error_message": f"JavaScript Syntax Error:\n{result.stderr}"}
        return {"error_message": None}

    # 3. Handle Compiled Languages (Go, Java, Rust, C++) using temporary file sandboxing
    elif lang in ["go", "golang", "java", "rust", "rs"]:
        # Map out the file extensions and compiler check commands
        lang_config = {
            "go": {"ext": ".go", "cmd": ["go", "vet"]},
            "golang": {"ext": ".go", "cmd": ["go", "vet"]},
            "rust": {"ext": ".rs", "cmd": ["rustc", "--allow", "dead_code", "--emit=mir"]},
            "rs": {"ext": ".rs", "cmd": ["rustc", "--allow", "dead_code", "--emit=mir"]},
            "java": {"ext": ".java", "cmd": ["javac"]}
        }
        
        cfg = lang_config[lang]
        
        # Write to a temporary file structure to invoke external compilers safely
        with tempfile.TemporaryDirectory() as tmpdir:
            # Java files must match public class names; defaulting target to Main.java
            filename = "Main.java" if lang == "java" else f"temp_src{cfg['ext']}"
            tmp_file_path = os.path.join(tmpdir, filename)
            
            with open(tmp_file_path, "w", encoding="utf-8") as tmp_file:
                tmp_file.write(code)
            
            # Run the syntax validation tool or compiler dry-run
            cmd = cfg["cmd"] + [tmp_file_path]
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode != 0:
                # Combine stdout and stderr since some compilers print warnings/errors to stdout
                errors = (result.stderr + "\n" + result.stdout).strip()
                return {"error_message": f"{lang.upper()} Compilation Error:\n{errors}"}
                
        return {"error_message": None}

    # 4. Fallback for unsupported validation layers
    else:
        print(f"Warning: No explicit validation engine configured for '{lang}'. Skipping verification.")
        return {"error_message": None}
